#mongosh to start mongodb
version: '3'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INIT_DB_ROOT_USERNAME=admin
      - MONGO_INIT_DB_ROOT_PASSWORD=admin

    